### ISSUE TITLE
The application has corrupted its heap memory area (address zero)!

### ISSUE THREAD

**Issue by patrickkh7788** [CyberShadow/dscripten-tools#1]
build worker.d show this warning.
```
warning: unresolved symbol: _D9dscripten10emscripten13workerRespondFAxvZv
warning: unresolved symbol: _D9dscripten10emscripten26workerRespondProvisionallyFAxvZv
warning: unresolved symbol: _Dmodule_ref
```

run on chrome and firefox throw error:

The application has corrupted its heap memory area (address zero)!

**Comment by CyberShadow** [comment]
What worker.d are you trying to build?

**Comment by patrickkh7788** [comment]
The demo on the readme page.

**Comment by CyberShadow** [comment]
Updated, it should work now.

I don't get the first two lines it the output though.

**Comment by patrickkh7788** [comment]
after I update code, it still give the warning.
```
warning: unresolved symbol: _D9dscripten10emscripten13workerRespondFAxvZv
warning: unresolved symbol: _D9dscripten10emscripten26workerRespondProvisionallyFAxvZv
warning: unresolved symbol: _Dmodule_ref
```

the js on chrome only show same error. (before it show 3 error, now only show one error)
Uncaught Runtime error: The application has corrupted its heap memory area (address zero)!
checkStackCookie @ worker.js:1124
preMain @ worker.js:1225
doRun @ worker.js:9064
run @ worker.js:9082
(anonymous) @ worker.js:9192

I run `rm -r ~/.emscripten_cache*` before build worker.d

**Comment by CyberShadow** [comment]
Can you run the test cases?

**Comment by patrickkh7788** [comment]
```
./run-tests.sh 
t0001-basic:
/tmp/.rdmd-0/rdmd-dmd-dscripten.d-61BE40AC85570A1DBF2C398AD85B3FF5/objs/dmd-dscripten.js.o: In function `_D4core6thread6Thread9termLocksFNiZv':
dmd2/linux/bin64/../../src/druntime/import/core/thread.d:1722: undefined reference to `_D4core4sync5mutex5Mutex6__dtorMFNiNeZv'
collect2: error: ld returned 1 exit status
Error: linker exited with status 1
```

**Comment by CyberShadow** [comment]
The tests run fine on my machine (Arch Linux) and on Travis CI, so, it looks like there is a problem with your local setup. You will need to figure it out yourself.

I suggest to try running the setup again. If that doesn't work, try in a fresh chroot or VM without any other D-related packages. Ultimately, you can try to replicate the Travis CI environment (there are public Docker images).
